steps:
  # Build the container image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=eu.gcr.io/$PROJECT_ID/farmhand:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=168h
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "farmhand"
      - "--image"
      - "eu.gcr.io/$PROJECT_ID/farmhand:$COMMIT_SHA"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
timeout: "1800s"
options:
  machineType: "E2_HIGHCPU_8"
